### PR TITLE
defmt_decoder: Bump dep `object` to `0.23.0`

### PR DESCRIPTION
**Pull request by Urhengulas**

### CODE REVIEW

**Comment by jonas-schievink** [comment]
This will duplicate the dependency in probe-run since 0.22 is still pulled in by other dependencies

**Comment by Urhengulas** [comment]
> This will duplicate the dependency in probe-run since 0.22 is still pulled in by other dependencies

Oh. Should we then push the dependency to update, or downgrade ourselves?

**Comment by jonas-schievink** [comment]
Let's keep using 0.22.0 for now to get this out the door

**Pull request merged**
