### PR TITLE
Implement `Format` for the `core::ops` structs.

### PR DESCRIPTION
**Pull request by derekdreery**

### CODE REVIEW

**Comment by Urhengulas** [comment]
Is it on purpose that `RangeTo` is omitted?

**Comment by derekdreery** [comment]
> Is it on purpose that `RangeTo` is omitted?

Oops! Added now :)

**Review by Urhengulas — APPROVED** [review]
Awesome!

bors r+

**Comment by Urhengulas** [comment]
I will add snapshot tests in a separate PR

**Pull request merged**
