### PR TITLE
`book`: Add logo and support text to introduction

### LINKED ISSUE #420: add knurling logo to the book
also link to the [knurling website](https://knurling.ferrous-systems.com/) and the GitHub sponsors page.

by 'the book' I mean https://defmt.ferrous-systems.com/

### PR DESCRIPTION
**Pull request by Urhengulas**
Fixes #420.

## preview
(https://deploy-preview-527--eager-mestorf-d2af88.netlify.app/)
Screenshot from 2021-07-05 18-55-23

### CODE REVIEW

**Comment by Mirabellensaft** [comment]
LGTM, but  for further iteration we should have the request for sponsoring visually separated from the content. Something like a banner or so.

**Review by Mirabellensaft — APPROVED** [review]

**Comment by Urhengulas** [comment]
bors stop

**Comment by Urhengulas** [comment]
bors cancel

**Comment by Urhengulas** [comment]
@Mirabellensaft What do you think about the added sponsor card (stolen from the knurling website)? Not quite a banner, but definitely more apparent.

**Pull request merged**
