### PR TITLE
Xtask qemu overwrite

### PR DESCRIPTION
**Pull request by derekdreery**
This adds an `--overwrite` option to the snapshot test, that overwrites the original output.

I've broken it out of #503 and will rebase once that is merged (in some form).

### CODE REVIEW

**Comment by Urhengulas** [comment]
@derekdreery Can you please rebase this? I hope it works even though GitHub detected it as merged 🤔

**Comment by Urhengulas** [comment]
@derekdreery ping 🔔

**Comment by derekdreery** [comment]
Hi I wasn't sure what to do. Do you want me to rebase the PR even though bors merged it?

**Comment by Urhengulas** [comment]
Hi, the xtask changes didn't land on master, since you reverted it in the other PR. It seems that GitHub still recognized this PR to be merged, since all of the commits of this PR are on the master branch.

So yes, please rebase and then it should only be the xtask changes. If it isn't possible to continue using this PR, since it is marked as merged, feel free to open a new one.

**Comment by derekdreery** [comment]
I feel like we've defeated github :stuck_out_tongue:

**Comment by Urhengulas** [comment]
> I feel like we've defeated github :stuck_out_tongue: 

Might be xD

**Pull request merged**
