### PR TITLE
Refactor rtt [1/2]

### PR DESCRIPTION
**Pull request by Urhengulas**
First half of #573:
*  defmt-rtt: Move struct Channel into own module
* defmt-rtt: Make fn host_is_connected a method of Channel
* defmt-rtt: Move struct Header into own module
* defmt-rtt: Rename fn handle to fn channel + mv to mod channel

### CODE REVIEW

**Comment by jonas-schievink** [comment]
Looks good! Although I think I'd prefer to drop 6874e9b, since that moves a lot more than just the `Header` struct, and the `_SEGGER_RTT` static is something that IMO doesn't belong buried in a `header` module. (this also needs a rebase after the recent RTT fixes, but other than that LGTM)

**Comment by Urhengulas** [comment]
> Looks good! Although I think I'd prefer to drop [6874e9b](https://github.com/knurling-rs/defmt/commit/6874e9b9229b2e9fc6a9e3549fda8f0da083dd2f), since that moves a lot more than just the `Header` struct, and the `_SEGGER_RTT` static is something that IMO doesn't belong buried in a `header` module. (this also needs a rebase after the recent RTT fixes, but other than that LGTM)

So - I would keep the `const`s and `static`s in the `lib.rs` and only move out the `struct Header`.

**Comment by Urhengulas** [comment]
@jonas-schievink Can you please take another look?

**Comment by jonas-schievink** [comment]
What do we gain from moving `Header` to another file? Since it only has 4 field and no methods, it doesn't use much code

**Comment by Urhengulas** [comment]
> What do we gain from moving `Header` to another file? Since it only has 4 field and no methods, it doesn't use much code

Actually true

**Comment by Urhengulas** [comment]
That's it?

**Pull request merged**
