### PR TITLE
Disable `unstable-test` on docs.rs

### PR DESCRIPTION
**Pull request by jonas-schievink**
https://github.com/knurling-rs/defmt/issues/409

### CODE REVIEW

**Comment by Urhengulas** [comment]
How can one test if this configuration works?

**Comment by jonas-schievink** [comment]
I tested this locally. I'm not aware of any convenient ways to test it in CI.

**Comment by jonas-schievink** [comment]
I ran:

```console
env RUSTDOCFLAGS=--cfg=docsrs cargo +nightly doc --features alloc --target thumbv6m-none-eabi --open
```

Replacing the `--features alloc` with `--all-features` reproduces the error on docs.rs.

**Review by japaric — APPROVED** [review]
Looks good to me!
By the way, was what the reason for specifying thumbv6 and thumbv7 as the docs.rs targets? we don't cfg public API based on the target (architecture), right? (`impl Format for Arc` doesn't exist on thumbv6 but `Arc` doesn't exist there either)

**Comment by jonas-schievink** [comment]
> `impl Format for Arc` doesn't exist on thumbv6 but `Arc` doesn't exist there either

It does exist on thumbv7, so it will show up in the docs for thumbv7

**Pull request merged**
