### PR TITLE
Impl `Format` for all `Cow`s

### PR DESCRIPTION
**Pull request by mattico**

### CODE REVIEW

**Comment by mattico** [comment]
Is that failure spurious? Can't understand why it would print out of order.

**Comment by jonas-schievink** [comment]
You're running into https://github.com/knurling-rs/defmt/issues/452, it's hiding the actual error:

```
error[E0433]: failed to resolve: use of undeclared type `Cow`
  --> qemu/src/bin/alloc.rs:40:38
   |
40 |     defmt::info!("Cow<[u32]>: {=?}", Cow::Borrowed(&[1, 2, 3, 4]));
   |                                      ^^^ not found in this scope
```

**Comment by jonas-schievink** [comment]
You can test this locally via `cd firmware/qemu && cargo rb alloc --features alloc`

**Review by Urhengulas — APPROVED** [review]
Thank you @mattico! 

bors r+

**Pull request merged**
