### PR TITLE
Deprecate ip_in_core feature

### PR DESCRIPTION
**Pull request by Urhengulas**
This PR removed the ip_in_core feature from `defmt` and re-enables nightly shapshot tests. See #803 for details.

### CODE REVIEW

**Comment by newAM** [comment]
Rust 1.77 is out! <https://blog.rust-lang.org/2024/03/21/Rust-1.77.0.html>

Would it be possible to get a release after this is merged?

**Comment by Urhengulas** [comment]
> Rust 1.77 is out! https://blog.rust-lang.org/2024/03/21/Rust-1.77.0.html
> 
> Would it be possible to get a release after this is merged?

Sure

**Comment by Urhengulas** [comment]
Removing a cargo feature is a breaking change, right?

**Comment by newAM** [comment]
> Removing a cargo feature is a breaking change, right?

Yes, but the feature can be left in (without doing anything) to avoid this.

**Comment by Urhengulas** [comment]
@newAM defmt 0.3.7 was released just now

**Pull request merged**
