### PR TITLE
v0.1.x CI: fix nightly build

### PR DESCRIPTION
**Pull request by Lotterleben**
cherry-pick https://github.com/knurling-rs/defmt onto our v0.1.x branch as well

### CODE REVIEW

**Comment by japaric** [comment]
(I think bors should also work on-main PRs?)

bors r+

**Comment by japaric** [comment]
right, the v0.1.x branch has no bors configuration

**Comment by Lotterleben** [comment]
It will in 2 minutes and a PR :)

**Review by japaric — APPROVED** [review]

**Pull request merged**
