### PR TITLE
[1/n] - Logger trait v2.

### PR DESCRIPTION
**Pull request by Dirbaio**
Part 1 of N of #492 

- Panics on reentrant acquire.
- Remove `Write` trait.

### CODE REVIEW

**Comment by Dirbaio** [comment]
Code size comparison of the `log` snapshot test:

```
                               before    after    change
- debug:                       114320   107232     -6.2%
- release:                      43264    40852     -5.5%
- release + flags:              24288    21936     -9.6%
- release + flags + buildstd:   22860    20524    -10.2%

"flags" means these in Cargo.toml:

codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 'z'
overflow-checks = false

"buildstd" means these in .cargo/config.toml:

[unstable]
build-std = ["core"]
build-std-features = ["panic_immediate_abort"]


```

**Review by jonas-schievink — APPROVED** [review]

**Comment by Urhengulas** [comment]
@Dirbaio: Even though the PR is approved now, we will wait with merging and do one other patch release with some minor changes. After this is released we can start merging breaking changes as much as we want 😅😆

**Comment by Dirbaio** [comment]
Sounds fair! Please don't let it grow many conflicts as rebasing these is super painful.

**Comment by Urhengulas** [comment]
> Sounds fair! Please don't let it grow many conflicts as rebasing these is super painful. sweat_smile

We'll try to be quick! 😁

**Comment by Urhengulas** [comment]
@Dirbaio: `defmt 0.2.3` is released and therefore we are ready to merge breaking changes! 🎉 

I will leave this to you or @jonas-schievink 😄

**Pull request merged**
