### PR TITLE
Make leb64 encoding fully safe

### PR DESCRIPTION
**Pull request by jonas-schievink**
This removes all unchecked indexing as well as the usage of `MaybeUninit::uninit().assume_init()` from the leb64 encoding logic.

Resulting binary size change for the `log` binary:

```
   text	   data	    bss	    dec	    hex	filename
  33708	      0	      8	  33716	   83b4	log-main
  33508	      0	      8	  33516	   82ec	../../target/thumbv7m-none-eabi/release/log
```

That's right, it's 200 Bytes smaller.

I've also tried keeping `MaybeUninit` in place, which reduces binary size by like 400 *more* bytes. That seemed spooky, so I didn't go for that (zeroing 10 bytes shouldn't take 400 Bytes of code space? does it pull in `memset`? does it miscompile something due to the UB?). Haven't investigated that further.

### CODE REVIEW

**Review by japaric — APPROVED** [review]
This is better. Thanks.

> That's right, it's 200 Bytes smaller.

was that with opt-level=3? maybe the indexing prevents loop unrolling and that makes the binary smaller? I would have no idea why keeping the assume-uninit makes the program that much smaller though. llvm optimizations are unpredictable IMO

**Comment by jonas-schievink** [comment]
> was that with opt-level=3?

It was `cargo build --release` in the `firmware/qemu` directory, which should be opt-level=3, LTO=fat.

**Comment by japaric** [comment]
needs a rebase but feel free to submit to bors once that's resolved

**Comment by jonas-schievink** [comment]
bors r=japaric

**Pull request merged**
