### PR TITLE
`defmt-test`: Exit with semihosting exit

### PR DESCRIPTION
**Pull request by Urhengulas**
This PR makes `probe-rs` detect exit as successfully. Basically the same as https://github.com/knurling-rs/app-template/pull/71.

### CODE REVIEW

**Review by jonathanpallant — APPROVED** [review]

**Comment by jonathanpallant** [comment]
LGTM. Can you post a log from a test run?

**Comment by Urhengulas** [comment]
`probe-run` does print `ERROR the program panicked` instead of `Error: CPU halted unexpectedly.`. Which I think is better. But I feel this is a separate topic of "Make `probe-rs` detect panics".

**Comment by Urhengulas** [comment]
@jonathanpallant Can I merge?

**Comment by Urhengulas** [comment]
I have to say that the `probe-run` backtrace actually looks better.

probe-run:
```text
ERROR panicked at src/lib.rs:25:5:
OMG!!!
└─ panic_probe::print_defmt::print @ /home/urhengulas/.cargo/git/checkouts/defmt-7f5b74b4e6ff55d4/e36e12a/firmware/panic-probe/src/lib.rs:104
────────────────────────────────────────────────────────────────────────────────
stack backtrace:
   0: HardFaultTrampoline
      <exception entry>
   1: lib::inline::__udf
        at ./asm/inline.rs:181:5
   2: __udf
        at ./asm/lib.rs:51:17
   3: cortex_m::asm::udf
        at /home/urhengulas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cortex-m-0.7.7/src/asm.rs:43:5
   4: panic_probe::hard_fault
        at /home/urhengulas/.cargo/git/checkouts/defmt-7f5b74b4e6ff55d4/e36e12a/firmware/panic-probe/src/lib.rs:86:5
   5: rust_begin_unwind
        at /home/urhengulas/.cargo/git/checkouts/defmt-7f5b74b4e6ff55d4/e36e12a/firmware/panic-probe/src/lib.rs:54:9
   6: core::panicking::panic_fmt
        at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   7: krate::abc
        at src/lib.rs:25:5
   8: main
        at tests/integration.rs:8:1
   9: Reset
(HOST) ERROR the program panicked
```

probe-rs
```text
ERROR panicked at src/lib.rs:25:5:
OMG!!!
└─ panic_probe::print_defmt::print @ /home/urhengulas/.cargo/git/checkouts/defmt-7f5b74b4e6ff55d4/e36e12a/firmware/panic-probe/src/lib.rs:104 
Frame 0: exp_u128 @ 0x00001bfc
Frame 1: __udf @ 0x00000b8c inline
       ./asm/lib.rs:48:1
Frame 2: __udf @ 0x0000000000000b8c
       ./asm/lib.rs:51:17
Frame 3: udf @ 0x00000410 inline
       /home/urhengulas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cortex-m-0.7.7/src/asm.rs:43:5
Frame 4: hard_fault @ 0x000000000000040c
       /home/urhengulas/.cargo/git/checkouts/defmt-7f5b74b4e6ff55d4/e36e12a/firmware/panic-probe/src/lib.rs:86:5
Frame 5: panic @ 0x000003f6
       /home/urhengulas/.cargo/git/checkouts/defmt-7f5b74b4e6ff55d4/e36e12a/firmware/panic-probe/src/lib.rs:54:9
Frame 6: exp_u128 @ 0x00000d1a
       /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/num/bignum.rs:195:17
Frame 7: abc @ 0x00000372
       /home/urhengulas/Documents/github.com/knurling-rs/krate/src/lib.rs:25:5
Frame 8: __defmt_test_entry @ 0x000002ac
       /home/urhengulas/Documents/github.com/knurling-rs/krate/tests/integration.rs:8:1
Frame 9: fmt @ 0x0000013c
Frame 10: fmt @ 0x0000013c
Error: CPU halted unexpectedly.
```

**Comment by Urhengulas** [comment]
> @jonathanpallant Can I merge?

I will just go ahead.

**Pull request merged**
