### PR TITLE
Use atomic_polyfill on targets without atomics

### PR DESCRIPTION
**Pull request by TheButlah**
Most targets, even those without atomic instructions, support atomic load and stores. RISC-V is one of the few platforms that lacks this ability, and rustc is planning on solving that in the future (https://github.com/rust-lang/rust/issues/99668).

However, in the meantime it is impossible to use `defmt-rtt` on the riscv non-atomic platform, such as the ESP32-C3.

`atomic-polyfill` is a useful crate that emulates the atomics via `critical_section`, *but only on platforms without atomic support*. On platforms with atomic support, it just re-exports the types from `core::sync::atomic`.

Would this PR be considered for inclusion in `defmt-rtt`? A prior PR was rejected here: https://github.com/knurling-rs/defmt/pull/702

### CODE REVIEW

**Comment by TheButlah** [comment]
To clarify: things have changed since then, chiefly these work now:
https://github.com/esp-rs/esp-hal/issues/191
https://github.com/esp-rs/esp-hal/issues/175

It works on -imac, but this PR will allow it to work on -imc also (preferred because it's not using a trap handler anymore)

**Comment by Urhengulas** [comment]
I will try  to come back to you about this next year

**Comment by Dirbaio** [comment]
`defmt-rtt` only uses atomic load/store, no CAS, so using `atomic-poyfill` shouldn't be necessary. It'll acquire/release the critical section unnecessarily for each load/store.

Since all accesses are done within a critical section already, I think they could be replaced with UnsafeCell + write/read_volatile + fences.

**Comment by Urhengulas** [comment]
> `defmt-rtt` only uses atomic load/store, no CAS, so using `atomic-poyfill` shouldn't be necessary. It'll acquire/release the critical section unnecessarily for each load/store.
> 
> Since all accesses are done within a critical section already, I think they could be replaced with UnsafeCell + write/read_volatile + fences.

Thank you @Dirbaio. Could you elaborate how "UnsafeCell + write/read_volatile + fences" would roughly look like?

**Comment by Dirbaio** [comment]
Using `UnsafeCell<u32>` instead of `AtomicU32`, and do volatile loads/stores to it. It's sound because these are always done within the critical section.

It's an ugly workaround though. Ideally Rust should expose load/store atomics on riscv32-imc (what the esp32c3 is) like it does in cortex-m. See relevant Rust issue: https://github.com/rust-lang/rust/issues/99668

**Comment by Urhengulas** [comment]
@TheButlah do you have bandwidth to change your PR to `UnsafeCell` as described by @adamgreig?

**Comment by TheButlah** [comment]
Is it really a good idea to add unsafe code when non-CAS atomics work fine?

I think the issue was more of a lack of knowledge about the relevant `-C` flags on my end. Ideally users could be educated that the following flags should be used on RISCV:

`.cargo/config.toml`
```
[target.riscv32imc-unknown-none-elf]
rustflags = [
  # enable the atomic codegen option for RISCV
  "-C", "target-feature=+a",

  # tell the core library have atomics even though it's not specified in the target definition.
  # NOTE: This is fine for load/store, but we don't support compare-and-swap, so we don't get
  # full atomic features. For that, atomic_polyfill or the atomic trap handler should be used
  # instead. But we don't need CAS in the firmware.
  "--cfg", "target_has_atomic_load_store",
  "--cfg", 'target_has_atomic_load_store="8"',
  "--cfg", 'target_has_atomic_load_store="16"',
  "--cfg", 'target_has_atomic_load_store="32"',
  "--cfg", 'target_has_atomic_load_store="ptr"',
]
```

**Comment by Urhengulas** [comment]
Sooo ... there aren't changes to defmt necessary? I am slightly unsure about the status.

**Comment by Dirbaio** [comment]
they're not, I think this can be closed.

It'll Just Work when https://github.com/rust-lang/rust/issues/99668 gets fixed for riscv. Until then users can use [these](https://github.com/knurling-rs/defmt/pull/707#issuecomment-1488035240) flags.

**Pull request closed without merging**
